export { mockConnectionEncrypter } from './connection-encrypter.js'
export { mockConnectionGater } from './connection-gater.js'
export { mockConnectionManager, mockNetwork } from './connection-manager.js'
export { mockConnection, mockStream, connectionPair } from './connection.js'
export { mockMultiaddrConnection, mockMultiaddrConnPair } from './multiaddr-connection.js'
export { mockMuxer } from './muxer.js'
export { mockRegistrar } from './registrar.js'
export { mockUpgrader } from './upgrader.js'
export { mockDuplex } from './duplex.js'
export type { MockUpgraderInit } from './upgrader.js'
export type { NetworkComponents } from './connection-manager.js'